name: examen_flutter
description: Examen de prueba de Felipe Osorio

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive_flutter: ^1.1.0
  http: ^0.13.5
  intl: ^0.17.0
  provider: ^6.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
